INSERT INTO COORDINATE (X, Y) VALUES (0, 1); --Adam
INSERT INTO COORDINATE (X, Y) VALUES (1, 1); --Eve
INSERT INTO COORDINATE (X, Y) VALUES (10, 6); --Monster
INSERT INTO MONSTER_STATUS (ID, POSITION_X, POSITION_Y, FACING) VALUES (100, 10, 6, 'UP');
INSERT INTO SHOWDOWN (ID, DESCRIPTION, GAME_STATUS, MONSTER_STATUS_ID) VALUES (103, 'game 1', 'RUNNING', 100);
INSERT INTO SURVIVOR (ID, NAME, IS_ALIVE, ACTIVATIONS_LEFT, MOVES_LEFT, MOVEMENT, SURVIVAL, INSANITY,
            POSITION_X, POSITION_Y, SHOWDOWN_ID)
            VALUES (101, 'Adam', true, 1, 1, 5, 0, 0, 0, 1, 103);
INSERT INTO SURVIVOR (ID, NAME, IS_ALIVE, ACTIVATIONS_LEFT, MOVES_LEFT, MOVEMENT, SURVIVAL, INSANITY,
            POSITION_X, POSITION_Y, SHOWDOWN_ID)
            VALUES (102, 'Eve', true, 1, 1, 5, 0, 0, 1, 1, 103);