INSERT INTO SHOWDOWN (ID, DESCRIPTION) VALUES (100, 'game 1')
INSERT INTO COORDINATE (X, Y) VALUES (0, 0)
INSERT INTO MONSTER_POSITION (X, Y, FACING) VALUES (0, 0, 'UP')
INSERT INTO MONSTER_STATUS (ID, MONSTER_POSITION_X, MONSTER_POSITION_Y, MONSTER_POSITION_FACING) VALUES (100, 0, 0, 'UP')